// TASKS

###
GET http://localhost:8080/tasks


###
POST http://localhost:8080/tasks
Content-Type: application/json

{
  "title": "swim",
  "description": "with friend",
  "priority": false,
  "project": "test project",
  "due": null
}

###
DELETE http://localhost:8080/tasks/67ee60aa2f42ab2b0df3d3e3





// PROJECTS


###
GET http://localhost:8080/projects

###
DELETE http://localhost:8080/projects/67faaa32361763ba20972054

###
POST http://localhost:8080/projects
Content-Type: application/json


{
    "name": "work"
}