// TASKS

###
GET http://localhost:8080/tasks


###
POST http://localhost:8080/tasks
Content-Type: application/json

{
  "title": "eeeessss",
  "description": "express 3",
  "priority": false,
  "project": "test project"

}

###
DELETE http://localhost:8080/tasks/67ee60aa2f42ab2b0df3d3e3





// PROJECTS


###
GET http://localhost:8080/projects

###
DELETE http://localhost:8080/projects/67feb8a855d7f17fc6ab941b

###
POST http://localhost:8080/projects
Content-Type: application/json


{
    
}



###
GET http://localhost:8080/example