###
GET http://localhost:8080/tasks


###
POST http://localhost:8080/tasks
Content-Type: application/json


{
    "title": "breakies",
    "description": "with friend",
  "priority": false,
  "project": "test project",
  "due": null
}

###
DELETE http://localhost:8080/tasks/67ebafaabba4719b091f7e0e
